### ISSUE TITLE
JSX/TSX file extension clashes with React/Hyperscript style file extensions

### ISSUE THREAD

**Issue by TomCaserta** [GodotExplorer/ECMAScript#23]
Great project and works fine as is just leaving this issue as the `jsx`/`tsx` file extensions used are pretty much exclusive to React/hyperscript. 

It's a little weird to adopt these in this project and causes some extensions in editors such as VSCode to believe that the file you are editing is of a react type. While it doesn't break anything it'd be nice not to have to disable/configure extensions in my editor to avoid react exclusive code suggestions/linting.

I would like to suggest changing this requirement to `js`/`ts` as in theory they are normal JS files without any additional syntax added.

**Comment by Geequlim** [comment]
In godot engine a *Script* is treaded as a class extends from `godot.Object`. So only a script export a class that extends from `godot.Object` is a valid godot script.

The godot editor always tries to parse all files with valid script extension as a godot class. But most of our .js files in project are not aimmed to be used by Node so they don't extends from `godot.Object`. In editor side the script is not a *Script*.
Therefore, I have to sperate them to two resource type. Scripts that can be mounted to Node use .jsx extension, to avoid the editor constantly trying to parse the .js files into classes.

Why is JSX
Because typescript can only compile files from ts to js and tsx to jsx.

**Comment by TomCaserta** [comment]
Thanks for the response, fair enough that makes sense :) 

I guess you could opt to use a sort of sub-extension in a way, for example `my-script.godot.js` or `my-script.godot.ts` which could work. Either way it's not much of a big deal, guess this ticket can be closed 👍
